services:

  trackr-db:
    container_name: trackr-db
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="TRADITIONAL"
    env_file: .env
    networks:
      - trackr

  trackr-web:
    container_name: trackr-web
    build: .
    image: trackr-web
    restart: always
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/z-extended-php.ini
    ports:
      - "8081:80"
    depends_on:
      - trackr-db
    networks:
      - trackr

  trackr-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: trackr-rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - trackr

  trackr-consumer:
    container_name: trackr-consumer
    build: ./src/rabbitmq
    image: trackr-amqp-consumer
    entrypoint: [ 'php', '/trackr/src/rabbitmq/consumer.php' ]
    volumes:
      - ./:/trackr
    restart: on-failure
    depends_on:
      - trackr-db
      - trackr-rabbitmq
    networks:
      - trackr

  trackr-redis:
    image: redis:7-alpine
    container_name: trackr-redis
    restart: always
    networks:
      - trackr

  trackr-typesense:
    image: typesense/typesense:27.0
    container_name: trackr-typesense
    restart: on-failure
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'
    networks:
      - trackr

volumes:
  typesense-data:
    driver: local
  db-data:
    driver: local

networks:
  trackr: