version: "3"

services:

  trackr-db:
    container_name: trackr-db
    image: mysql:5.7
    restart: always
    volumes:
      - ./database/trackr-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="TRADITIONAL"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Europe/Istanbul'
    networks:
      - trackr

  trackr-web:
    container_name: trackr-web
    build: .
    image: trackr-web
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - trackr-db
    networks:
      - trackr

  trackr-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: trackr-rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - trackr

  trackr-consumer:
    container_name: trackr-consumer
    build: ./src/rabbitmq
    image: trackr-amqp-consumer
    entrypoint: [ 'php', '/trackr/src/rabbitmq/consumer.php' ]
    volumes:
      - ./:/trackr
    restart: on-failure
    depends_on:
      - trackr-db
      - trackr-rabbitmq
    networks:
      - trackr

  trackr-redis:
    image: redis:7-alpine
    container_name: trackr-redis
    restart: always
    networks:
      - trackr

networks:
  trackr: